// generated by pronto from the cel: constraints in program.cue — do not edit
//
// `checks` are the SQL CHECK bodies emit.cue renders into the table DDL;
// `seed` carries what each field-level cel says about the field's own
// value, which is what vets a stated row; `enums` lists the values a
// closed constraint admits, for the readers that cannot enumerate a CUE
// disjunction, and `bounds` states what an open one admits — a range, a
// length, a pattern — for the readers that have to propose a value.
// An invariant binds `this` to the ROW, and a predicate over
// several columns constrains no single field's value, so it derives a
// CHECK body and nothing for CUE.
package shadcnui

import "strings"

code: state: entities: {
	SwitchDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			checked?: ("true" | "false")
		}]
		enums: {
			checked: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	TabsDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			active?: ("account" | "password")
			sel_account?: ("true" | "false")
			sel_password?: ("true" | "false")
			tab_account?: ("0" | "-1")
			tab_password?: ("0" | "-1")
		}]
		enums: {
			active: ["account","password"]
			sel_account: ["true","false"]
			sel_password: ["true","false"]
			tab_account: ["0","-1"]
			tab_password: ["0","-1"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	PickerDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			choice?: ("apple" | "banana" | "cherry")
			label?: strings.MaxRunes(24)
			sel_apple?: ("true" | "false")
			sel_banana?: ("true" | "false")
			sel_cherry?: ("true" | "false")
		}]
		enums: {
			choice: ["apple","banana","cherry"]
			sel_apple: ["true","false"]
			sel_banana: ["true","false"]
			sel_cherry: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
			label: {sizeMax: 24}
		}
	}
	ToggleGroupDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			value?: ("left" | "center" | "right")
			chk_left?: ("true" | "false")
			chk_center?: ("true" | "false")
			chk_right?: ("true" | "false")
			tab_left?: ("0" | "-1")
			tab_center?: ("0" | "-1")
			tab_right?: ("0" | "-1")
		}]
		enums: {
			value: ["left","center","right"]
			chk_left: ["true","false"]
			chk_center: ["true","false"]
			chk_right: ["true","false"]
			tab_left: ["0","-1"]
			tab_center: ["0","-1"]
			tab_right: ["0","-1"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	AccordionSingleDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			open?: ("none" | "shipping" | "returns" | "support")
			exp_shipping?: ("true" | "false")
			exp_returns?: ("true" | "false")
			exp_support?: ("true" | "false")
			caret?: ("shipping" | "returns" | "support")
			cur_shipping?: ("true" | "false")
			cur_returns?: ("true" | "false")
			cur_support?: ("true" | "false")
		}]
		enums: {
			open: ["none","shipping","returns","support"]
			exp_shipping: ["true","false"]
			exp_returns: ["true","false"]
			exp_support: ["true","false"]
			caret: ["shipping","returns","support"]
			cur_shipping: ["true","false"]
			cur_returns: ["true","false"]
			cur_support: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	AccordionMultiDemo: {
		seed: [...{
			id?: ("shipping" | "returns" | "support")
			open?: ("true" | "false")
		}]
		enums: {
			id: ["shipping","returns","support"]
			open: ["true","false"]
		}
	}
	ComboboxDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			choice?: ("Next.js" | "SvelteKit" | "Nuxt" | "Remix" | "Astro")
		}]
		enums: {
			choice: ["Next.js","SvelteKit","Nuxt","Remix","Astro"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	CheckboxDemo: {
		seed: [...{
			id?: ("terms")
			checked?: ("true" | "false")
		}]
		enums: {
			id: ["terms"]
			checked: ["true","false"]
		}
	}
	SelectAllDemo: {
		seed: [...{
			id?: ("all")
			phase?: ("live")
			checked?: ("true" | "false" | "mixed")
			inc_docs?: ("true" | "false")
			inc_images?: ("true" | "false")
			inc_archive?: ("true" | "false")
		}]
		enums: {
			id: ["all"]
			phase: ["live"]
			checked: ["true","false","mixed"]
			inc_docs: ["true","false"]
			inc_images: ["true","false"]
			inc_archive: ["true","false"]
		}
	}
	ToggleDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			pressed?: ("true" | "false")
		}]
		enums: {
			pressed: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	CollapsibleDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			open?: ("true" | "false")
		}]
		enums: {
			open: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	RadioGroupDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			value?: ("starter" | "pro" | "team")
			chk_starter?: ("true" | "false")
			chk_pro?: ("true" | "false")
			chk_team?: ("true" | "false")
			tab_starter?: ("0" | "-1")
			tab_pro?: ("0" | "-1")
			tab_team?: ("0" | "-1")
		}]
		enums: {
			value: ["starter","pro","team"]
			chk_starter: ["true","false"]
			chk_pro: ["true","false"]
			chk_team: ["true","false"]
			tab_starter: ["0","-1"]
			tab_pro: ["0","-1"]
			tab_team: ["0","-1"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	PaginationDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			page?: ("p1" | "p2" | "p3" | "p4" | "p5")
			cur_p1?: ("page" | "false")
			cur_p2?: ("page" | "false")
			cur_p3?: ("page" | "false")
			cur_p4?: ("page" | "false")
			cur_p5?: ("page" | "false")
			dis_prev?: ("" | "disabled")
			dis_next?: ("" | "disabled")
		}]
		enums: {
			page: ["p1","p2","p3","p4","p5"]
			cur_p1: ["page","false"]
			cur_p2: ["page","false"]
			cur_p3: ["page","false"]
			cur_p4: ["page","false"]
			cur_p5: ["page","false"]
			dis_prev: ["","disabled"]
			dis_next: ["","disabled"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	CarouselDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			slide?: ("s1" | "s2" | "s3" | "s4")
			cur_s1?: ("true" | "false")
			cur_s2?: ("true" | "false")
			cur_s3?: ("true" | "false")
			cur_s4?: ("true" | "false")
			dis_prev?: ("" | "disabled")
			dis_next?: ("" | "disabled")
		}]
		enums: {
			slide: ["s1","s2","s3","s4"]
			cur_s1: ["true","false"]
			cur_s2: ["true","false"]
			cur_s3: ["true","false"]
			cur_s4: ["true","false"]
			dis_prev: ["","disabled"]
			dis_next: ["","disabled"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	ToastDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			state?: ("closed" | "open")
		}]
		enums: {
			state: ["closed","open"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	SliderDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			phase?: ("live")
			volume?: >=0 & <=100
		}]
		enums: {
			phase: ["live"]
		}
		bounds: {
			id: {sizeMax: 64}
			volume: {intMin: 0, intMax: 100}
		}
	}
	ProgressDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			done?: >=0 & <=100
		}]
		bounds: {
			id: {sizeMax: 64}
			done: {intMin: 0, intMax: 100}
		}
	}
	ResizableDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			state?: "sizing"
			split?: >=15 & <=85
		}]
		enums: {
			state: ["sizing"]
		}
		bounds: {
			id: {sizeMax: 64}
			split: {intMin: 15, intMax: 85}
		}
	}
	CommandDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			state?: "typing"
			query?: strings.MaxRunes(64)
			active?: strings.MaxRunes(32)
			chosen?: strings.MaxRunes(32)
		}]
		enums: {
			state: ["typing"]
		}
		bounds: {
			id: {sizeMax: 64}
			query: {sizeMax: 64}
			active: {sizeMax: 32}
			chosen: {sizeMax: 32}
		}
	}
	CommandItem: {
		seed: [...{
			id?: strings.MaxRunes(32)
			label?: strings.MaxRunes(32)
			group?: strings.MaxRunes(32)
			pos?: >=1
		}]
		bounds: {
			id: {sizeMax: 32}
			label: {sizeMax: 32}
			group: {sizeMax: 32}
			pos: {intMin: 1}
		}
	}
	SelectDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			choice?: strings.MaxRunes(24)
		}]
		bounds: {
			id: {sizeMax: 64}
			choice: {sizeMax: 24}
		}
	}
	SelectOption: {
		seed: [...{
			id?: strings.MinRunes(1) & strings.MaxRunes(24)
		}]
		bounds: {
			id: {sizeMin: 1, sizeMax: 24}
		}
	}
	MenuOptionDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			chk_bookmarks?: ("true" | "false")
			chk_urls?: ("true" | "false")
			caret?: ("bookmarks" | "urls")
			cur_bookmarks?: ("true" | "false")
			cur_urls?: ("true" | "false")
			prefix?: strings.MaxRunes(32)
		}]
		enums: {
			chk_bookmarks: ["true","false"]
			chk_urls: ["true","false"]
			caret: ["bookmarks","urls"]
			cur_bookmarks: ["true","false"]
			cur_urls: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
			prefix: {sizeMax: 32}
		}
	}
	MenuGoDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			caret?: ("tabs" | "accordion" | "toast")
			cur_tabs?: ("true" | "false")
			cur_accordion?: ("true" | "false")
			cur_toast?: ("true" | "false")
			prefix?: strings.MaxRunes(32)
		}]
		enums: {
			caret: ["tabs","accordion","toast"]
			cur_tabs: ["true","false"]
			cur_accordion: ["true","false"]
			cur_toast: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
			prefix: {sizeMax: 32}
		}
	}
	MenubarDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			caret?: ("view" | "go")
			cur_view?: ("true" | "false")
			cur_go?: ("true" | "false")
			tab_view?: ("0" | "-1")
			tab_go?: ("0" | "-1")
		}]
		enums: {
			caret: ["view","go"]
			cur_view: ["true","false"]
			cur_go: ["true","false"]
			tab_view: ["0","-1"]
			tab_go: ["0","-1"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	ContextMenuDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			open?: ("true" | "false")
			x?: >=0 & <=1000
			y?: >=0 & <=1000
			caret?: ("popover" | "sheet" | "overlays")
			cur_popover?: ("true" | "false")
			cur_sheet?: ("true" | "false")
			cur_overlays?: ("true" | "false")
			prefix?: strings.MaxRunes(32)
		}]
		enums: {
			open: ["true","false"]
			caret: ["popover","sheet","overlays"]
			cur_popover: ["true","false"]
			cur_sheet: ["true","false"]
			cur_overlays: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
			x: {intMin: 0, intMax: 1000}
			y: {intMin: 0, intMax: 1000}
			prefix: {sizeMax: 32}
		}
	}
	MenuProfileDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			profile?: ("andy" | "benoit" | "luis")
			chk_andy?: ("true" | "false")
			chk_benoit?: ("true" | "false")
			chk_luis?: ("true" | "false")
			caret?: ("switch" | "checkbox" | "radio_group" | "andy" | "benoit" | "luis")
			cur_switch?: ("true" | "false")
			cur_checkbox?: ("true" | "false")
			cur_radio_group?: ("true" | "false")
			cur_andy?: ("true" | "false")
			cur_benoit?: ("true" | "false")
			cur_luis?: ("true" | "false")
			prefix?: strings.MaxRunes(32)
		}]
		enums: {
			profile: ["andy","benoit","luis"]
			chk_andy: ["true","false"]
			chk_benoit: ["true","false"]
			chk_luis: ["true","false"]
			caret: ["switch","checkbox","radio_group","andy","benoit","luis"]
			cur_switch: ["true","false"]
			cur_checkbox: ["true","false"]
			cur_radio_group: ["true","false"]
			cur_andy: ["true","false"]
			cur_benoit: ["true","false"]
			cur_luis: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
			prefix: {sizeMax: 32}
		}
	}
	FormDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			handle?: =~ "^[a-z][a-z0-9_]{2,23}$"
			bio?: strings.MaxRunes(240)
		}]
		bounds: {
			id: {sizeMax: 64}
			handle: {regex: "^[a-z][a-z0-9_]{2,23}$"}
			bio: {sizeMax: 240}
		}
	}
	TableRow: {
		seed: [...{
			id?: strings.MinRunes(1) & strings.MaxRunes(24)
			payer?: strings.MaxRunes(48)
			status?: ("Paid" | "Pending" | "Unpaid")
			amount?: strings.MaxRunes(12)
		}]
		enums: {
			status: ["Paid","Pending","Unpaid"]
		}
		bounds: {
			id: {sizeMin: 1, sizeMax: 24}
			payer: {sizeMax: 48}
			amount: {sizeMax: 12}
		}
	}
	TableQuery: {
		seed: [...{
			id?: strings.MaxRunes(64)
			state?: ("pending" | "typing")
			query?: strings.MaxRunes(48)
		}]
		enums: {
			state: ["pending","typing"]
		}
		bounds: {
			id: {sizeMax: 64}
			query: {sizeMax: 48}
		}
	}
	DataRow: {
		seed: [...{
			id?: strings.MinRunes(1) & strings.MaxRunes(24)
			payer?: strings.MaxRunes(48)
			status?: ("Paid" | "Pending" | "Unpaid")
			amount?: strings.MaxRunes(12)
		}]
		enums: {
			status: ["Paid","Pending","Unpaid"]
		}
		bounds: {
			id: {sizeMin: 1, sizeMax: 24}
			payer: {sizeMax: 48}
			amount: {sizeMax: 12}
		}
	}
	DataCursor: {
		seed: [...{
			id?: strings.MaxRunes(64)
			state?: "typing"
			query?: strings.MaxRunes(48)
			cursor?: strings.MaxRunes(24)
			sort?: ("id_asc" | "id_desc" | "amount_asc" | "amount_desc")
			srt_id?: ("ascending" | "descending" | "none")
			srt_amount?: ("ascending" | "descending" | "none")
		}]
		enums: {
			state: ["typing"]
			sort: ["id_asc","id_desc","amount_asc","amount_desc"]
			srt_id: ["ascending","descending","none"]
			srt_amount: ["ascending","descending","none"]
		}
		bounds: {
			id: {sizeMax: 64}
			query: {sizeMax: 48}
			cursor: {sizeMax: 24}
		}
	}
	NavRailItem: {
		seed: [...{
			id?: =~ "^[a-z-]{1,32}$"
			label?: strings.MaxRunes(32)
			route?: =~ "^[a-z-]{1,32}$"
			pos?: >=1 & <=99
		}]
		bounds: {
			id: {regex: "^[a-z-]{1,32}$"}
			label: {sizeMax: 32}
			route: {regex: "^[a-z-]{1,32}$"}
			pos: {intMin: 1, intMax: 99}
		}
	}
	NavState: {
		seed: [...{
			id?: strings.MaxRunes(64)
			current?: =~ "^[a-z-]{1,32}$"
		}]
		bounds: {
			id: {sizeMax: 64}
			current: {regex: "^[a-z-]{1,32}$"}
		}
	}
	NavSidebarDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			open?: ("true" | "false")
		}]
		enums: {
			open: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
		}
	}
	OtpDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			state?: ("typing" | "complete" | "verified")
			code?: strings.MaxRunes(6)
			invalid?: ("true" | "false")
			blocked?: ("" | "disabled")
		}]
		enums: {
			state: ["typing","complete","verified"]
			invalid: ["true","false"]
			blocked: ["","disabled"]
		}
		bounds: {
			id: {sizeMax: 64}
			code: {sizeMax: 6}
		}
	}
	ChartPoint: {
		seed: [...{
			id?: strings.MaxRunes(16)
			label?: strings.MaxRunes(24)
			value?: >=0
			pos?: >=1 & <=24
			nxt_value?: >=0
		}]
		bounds: {
			id: {sizeMax: 16}
			label: {sizeMax: 24}
			value: {intMin: 0}
			pos: {intMin: 1, intMax: 24}
			nxt_value: {intMin: 0}
		}
	}
	ChartCursor: {
		seed: [...{
			id?: strings.MaxRunes(64)
			active?: strings.MaxRunes(16)
		}]
		bounds: {
			id: {sizeMax: 64}
			active: {sizeMax: 16}
		}
	}
	CompositionDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			phase?: ("live")
			query?: strings.MaxRunes(64)
			last?: strings.MaxRunes(32)
		}]
		enums: {
			phase: ["live"]
		}
		bounds: {
			id: {sizeMax: 64}
			query: {sizeMax: 64}
			last: {sizeMax: 32}
		}
	}
	ChatRow: {
		seed: [...{
			id?: strings.MaxRunes(64)
			kind?: ("message" | "marker" | "file")
			seat?: ("you" | "them" | "none")
			who?: strings.MaxRunes(24)
			initials?: strings.MaxRunes(2)
			body?: strings.MaxRunes(120)
			note?: strings.MaxRunes(48)
			when?: strings.MaxRunes(12)
			at?: strings.MaxRunes(32)
			state?: ("done" | "uploading" | "error")
		}]
		enums: {
			kind: ["message","marker","file"]
			seat: ["you","them","none"]
			state: ["done","uploading","error"]
		}
		bounds: {
			id: {sizeMax: 64}
			who: {sizeMax: 24}
			initials: {sizeMax: 2}
			body: {sizeMax: 120}
			note: {sizeMax: 48}
			when: {sizeMax: 12}
			at: {sizeMax: 32}
		}
	}
	ChatDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
		}]
		bounds: {
			id: {sizeMax: 64}
		}
	}
	QuizDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			step?: ("one" | "two" | "three" | "done")
			a_shape?: strings.MaxRunes(32)
			a_state?: strings.MaxRunes(32)
			a_note?: strings.MaxRunes(80)
			blocked?: ("" | "disabled")
			sel_one_markup?: ("true" | "false")
			sel_one_chart?: ("true" | "false")
			sel_one_library?: ("true" | "false")
			sel_two_row?: ("true" | "false")
			sel_two_dom?: ("true" | "false")
			sel_two_memory?: ("true" | "false")
		}]
		enums: {
			step: ["one","two","three","done"]
			blocked: ["","disabled"]
			sel_one_markup: ["true","false"]
			sel_one_chart: ["true","false"]
			sel_one_library: ["true","false"]
			sel_two_row: ["true","false"]
			sel_two_dom: ["true","false"]
			sel_two_memory: ["true","false"]
		}
		bounds: {
			id: {sizeMax: 64}
			a_shape: {sizeMax: 32}
			a_state: {sizeMax: 32}
			a_note: {sizeMax: 80}
		}
	}
	CalendarDemo: {
		seed: [...{
			id?: strings.MaxRunes(64)
			state?: ("browsing")
			month?: strings.MinRunes(7) & strings.MaxRunes(7)
			label?: strings.MaxRunes(24)
			value?: strings.MaxRunes(16)
			active?: strings.MaxRunes(16)
		}]
		enums: {
			state: ["browsing"]
		}
		bounds: {
			id: {sizeMax: 64}
			month: {sizeMin: 7, sizeMax: 7}
			label: {sizeMax: 24}
			value: {sizeMax: 16}
			active: {sizeMax: 16}
		}
	}
	CalendarCell: {
		seed: [...{
			id?: strings.MaxRunes(16)
			grid?: strings.MinRunes(7) & strings.MaxRunes(7)
			month?: strings.MinRunes(7) & strings.MaxRunes(7)
			week?: ("w1" | "w2" | "w3" | "w4" | "w5" | "w6")
			dow?: ("d0" | "d1" | "d2" | "d3" | "d4" | "d5" | "d6")
			pos?: >=1 & <=42
			colpos?: >=0 & <=65
			day?: strings.MaxRunes(2)
			date?: strings.MinRunes(10) & strings.MaxRunes(10)
		}]
		enums: {
			week: ["w1","w2","w3","w4","w5","w6"]
			dow: ["d0","d1","d2","d3","d4","d5","d6"]
		}
		bounds: {
			id: {sizeMax: 16}
			grid: {sizeMin: 7, sizeMax: 7}
			month: {sizeMin: 7, sizeMax: 7}
			pos: {intMin: 1, intMax: 42}
			colpos: {intMin: 0, intMax: 65}
			day: {sizeMax: 2}
			date: {sizeMin: 10, sizeMax: 10}
		}
	}
}
