// generated by pronto from the layout this app is built in — do not edit

package shadcnui

loop: surface: sources: pronto: "../../plugins/pronto"
build: meta: dir: "apps/shadcnui"
cluster: meta: root: "../../"
cluster: meta: runtime: "../../"
